2024-01-23 13:43:29,172 CRIT Supervisor is running as root.  Privileges were not dropped because no user is specified in the config file.  If you intend to run as root, you can set user=root in the config file to avoid this message.
2024-01-23 13:43:29,173 INFO supervisord started with pid 7
2024-01-23 13:43:30,176 INFO spawned: 'app' with pid 8
2024-01-23 13:43:30,177 INFO spawned: 'nginx' with pid 9
2024-01-23 13:43:31,200 INFO success: app entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2024-01-23 13:43:31,200 INFO success: nginx entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
Bottle v0.12.25 server starting up (using WSGIRefServer())...
Listening on http://localhost:5000/
Hit Ctrl-C to quit.

[CTRL] POST /setup
[Time: 23.01.24 13:43:34] [Level: info] id: 23e85175121f42db
[Time: 23.01.24 13:43:34] [Level: info] coordinator: True
[Time: 23.01.24 13:43:34] [Level: info] clients: ['6617e54340b1c6be', '23e85175121f42db']
127.0.0.1 - - [23/Jan/2024 13:43:34] "POST /api/setup HTTP/1.0" 200 0
[Time: 23.01.24 13:43:34] [Level: info] state: initial
[Time: 23.01.24 13:43:34] [Level: info] [State: initial] <class 'abc.ABCMeta'>
[Time: 23.01.24 13:43:34] [Level: info] [State: initial] Error ...
[Time: 23.01.24 13:43:34] [Level: info] [State: initial] Error ...
[Time: 23.01.24 13:43:34] [Level: info] [State: initial] Error ...
[Time: 23.01.24 13:43:34] [Level: info] [State: initial] Error ...
[Time: 23.01.24 13:43:34] [Level: info] [State: initial] Error ...
[Time: 23.01.24 13:43:34] [Level: info] [State: initial] Reading training data ...
127.0.0.1 - - [23/Jan/2024 13:43:34] "GET /api/status HTTP/1.0" 200 155
[Time: 23.01.24 13:43:34] [Level: info] Traceback (most recent call last):
  File "/root/.local/lib/python3.8/site-packages/FeatureCloud/app/engine/app.py", line 251, in guarded_run
    self.run()
  File "/root/.local/lib/python3.8/site-packages/FeatureCloud/app/engine/app.py", line 270, in run
    transition = self.current_state.run()
  File "/app/states.py", line 159, in run
    train_dataset = torch.load(f'{INPUT_DIR}/train_dataset.pth')
  File "/root/.local/lib/python3.8/site-packages/torch/serialization.py", line 986, in load
    with _open_file_like(f, 'rb') as opened_file:
  File "/root/.local/lib/python3.8/site-packages/torch/serialization.py", line 435, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "/root/.local/lib/python3.8/site-packages/torch/serialization.py", line 416, in __init__
    super().__init__(open(name, mode))
FileNotFoundError: [Errno 2] No such file or directory: '/mnt/input/train_dataset.pth'

